// Time to throw your first error! 
// Simply throw a new error inside the throwError function.
// If you throw an error properly the tests will catch the error 
// and you will pass the stage!

function throwError() {
    throw new Error("Error people run :D");
}
